async function abrirScanner(){if(!datosExcel.workbook){alert('Primero cargue un archivo Excel.');return;}document.getElementById('scannerModal').classList.remove('hidden');document.getElementById('scanResult').classList.add('hidden');document.getElementById('btnIngresarManual').classList.remove('hidden');document.getElementById('btnSalirScanner').classList.remove('hidden');bloqueandoLectura=false;scannerActivo=true;try{if(scanner){try{await scanner.stop();}catch(e){}}scanner=new Html5Qrcode('reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:130},formatsToSupport:[Html5QrcodeSupportedFormats.CODE_128,Html5QrcodeSupportedFormats.CODE_39,Html5QrcodeSupportedFormats.CODE_93,Html5QrcodeSupportedFormats.CODABAR,Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E,Html5QrcodeSupportedFormats.ITF]},t=>{if(!bloqueandoLectura)procesarCodigo(t);});document.getElementById('scannerStatus').textContent='Apunte la cámara al código de barras';}catch(e){console.error(e);document.getElementById('scannerStatus').textContent='No se pudo acceder a la cámara. Use el ingreso manual.';}}
function detenerCamara(){if(scanner&&scannerActivo){scanner.stop().catch(()=>{});scannerActivo=false;}}
function procesarCodigo(codigo){bloqueandoLectura=true;detenerCamara();const c=normalizar(codigo);const exactos=vehiculos.filter(v=>key(v.chasis)===key(c));if(exactos.length)mostrarVehiculo(exactos[0]);else mostrarNoEncontrado(c);}
function mostrarVehiculo(v){vehiculoActual=v;document.getElementById('scanTitulo').textContent='Vehículo encontrado';document.getElementById('scanInfo').innerHTML=`<div class="scan-info"><strong>Chasis:</strong> ${escapeHTML(v.chasis)}<br>${escapeHTML(ubicacionTexto(v))}${v.movidoDesde?`<div class="vehicle-moved">Movido desde: ${escapeHTML(v.movidoDesde)}</div>`:''}</div>`;document.getElementById('scanButtons').innerHTML=`<button class="btn-secondary" onclick="cancelarResultadoScan()">Cancelar</button><button class="btn-danger" onclick="borrarDesdeScan()">Borrar</button><button class="btn-warning" onclick="cambiarDesdeScan()">Cambiar ubicación</button>`;document.getElementById('scanResult').classList.remove('hidden');document.getElementById('btnIngresarManual').classList.add('hidden');document.getElementById('btnSalirScanner').classList.add('hidden');}
function mostrarNoEncontrado(c){vehiculoActual={id:'nuevo-'+Date.now(),chasis:c,playa:'',bloque:'',carril:'',posicion:'',observaciones:''};modoCambio='nuevo';document.getElementById('scanTitulo').textContent='El vehículo no está en el listado';document.getElementById('scanInfo').innerHTML=`<div class="scan-info"><strong>Chasis escaneado:</strong> ${escapeHTML(c)}<br>Puede salir o indicar una nueva ubicación para agregarlo al Excel cargado.</div>`;document.getElementById('scanButtons').innerHTML=`<button class="btn-secondary" onclick="cerrarScanner()">Salir</button><button class="btn-warning" onclick="cambiarDesdeScan()">Cambiar ubicación</button>`;document.getElementById('scanResult').classList.remove('hidden');document.getElementById('btnIngresarManual').classList.add('hidden');document.getElementById('btnSalirScanner').classList.add('hidden');}
function cancelarResultadoScan(){document.getElementById('scanResult').classList.add('hidden');document.getElementById('btnIngresarManual').classList.remove('hidden');document.getElementById('btnSalirScanner').classList.remove('hidden');bloqueandoLectura=false;abrirScanner();}
function borrarDesdeScan(){if(!vehiculoActual)return;eliminarVehiculo(vehiculoActual.id);cerrarScanner();}
function cambiarDesdeScan(){abrirCambioUbicacionVehiculo(vehiculoActual.id,vehiculoActual);}
async function cerrarScanner(){detenerCamara();try{if(scanner)scanner.clear();}catch(e){}scanner=null;scannerActivo=false;document.getElementById('scannerModal').classList.add('hidden');bloqueandoLectura=false;}
function abrirIngresoManual(){document.getElementById('manualCodeModal').classList.remove('hidden');document.getElementById('manualCodeInput').value='';setTimeout(()=>document.getElementById('manualCodeInput').focus(),50);}
function cerrarIngresoManual(){document.getElementById('manualCodeModal').classList.add('hidden');}
function confirmarIngresoManual(){const c=normalizar(document.getElementById('manualCodeInput').value);if(c.length<4){alert('Ingrese al menos 4 caracteres.');return;}cerrarIngresoManual();const r=vehiculos.filter(v=>key(v.chasis).includes(key(c)));if(r.length===1){bloqueandoLectura=true;detenerCamara();mostrarVehiculo(r[0]);return;}if(r.length>1){mostrarCoincidencias(r);return;}bloqueandoLectura=true;detenerCamara();mostrarNoEncontrado(c);}
function mostrarCoincidencias(r){document.getElementById('listaCoincidencias').innerHTML=r.map(v=>`<button class="coincidencia-item" onclick="seleccionarCoincidencia('${v.id}')"><strong>${escapeHTML(v.chasis)}</strong><br><span>${escapeHTML(ubicacionTexto(v))}</span></button>`).join('');document.getElementById('coincidenciasModal').classList.remove('hidden');}
function cerrarCoincidencias(){document.getElementById('coincidenciasModal').classList.add('hidden');}
function seleccionarCoincidencia(id){cerrarCoincidencias();bloqueandoLectura=true;detenerCamara();const v=vehiculos.find(x=>x.id===id);if(v)mostrarVehiculo(v);}
